# Generated by Django 4.2.3 on 2023-08-08 05:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galleries', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercategory',
            unique_together={('category', 'user', 'author')},
        ),
    ]
